### PR TITLE
Add -g option for attaching to existing group

### LINKED ISSUE #19: attach new session in group
With tmux you can create a new session and attach it to an existing session in a group. Both sessions share the same windows and panes but you can view a different window concurrently in each session:

`$ tmux new-session -t existing-session-name`

This is really useful when trying to put different windows from the same session on different physical screens.

It would be nice to be able to do to something like `$ twm -g`, fuzzy find over workspaces, select one and have it create a new session grouped with an existing session in the same workspace instead of just attaching to the existing session.

### PR DESCRIPTION
**Pull request by vinnymeller**
Adds an option `-g/--group` that opens a fuzzy finder with current sessions, and starts a new session in a group with  the selected session

note: you can still use `-g` with `-d` and `-n`

closes #19

### CODE REVIEW

**Comment by vinnymeller** [comment]
@tombuntus do/can you build this yourself to see if this does what you're hoping? or do you just use binary from nix or something?

**Comment by vinnymeller** [comment]
i originally wanted to avoid adding a fuzzy search through existing sessions but i think it makes sense for this use case, so if this is working i'm also going to add `-e/--existing` to fuzzy find through open sessions and attach normally

**Comment by tombuntus** [comment]
I will try and build it later today. I have been giving this some thought and I wonder if a better workflow might be to just add an indicator alongside workspaces that already have a session in the regular twm workspace list, and then have enter attach to that session but ctrl+enter create a new session in a session group.

If we fuzzy find over existing sessions, then realise that the workspace we want to open doesn't have an existing session, we have to exit and relaunch twm to find the workspace and create a new session.

**Comment by vinnymeller** [comment]
@tombuntus i think both can coexist. e.g. i imagine that most of the time that I want to have a second session in a _group_, it's probably because I already have the original session open and thus obviously know that session exists. maybe not though?

but a factor I like about the current `-g` and `-e` implementation (which I didnt push yet but is same) is that it doesn't have to parse config or do any searching for workspaces, so its very snappy

but i agree adding something like a ctrl+enter to the normal twm to open a new group would be very neat

**Comment by tombuntus** [comment]
> i imagine that most of the time that I want to have a second session in a group, it's probably because I already have the original session open and thus obviously know that session exists

This is probably fair. I do often forget that I already have a client attached to a session, but that's a different issue I think.

I have built this branch and yes it works 👌 A nice side effect is that I can see when I already have a session group I forgot about.

**Pull request merged**
